"""Seed the collection schema and bring the existing case book into it.

Reference data first (types, sources, priorities, queues, workflow, rules),
then every existing customer_schema.debt_case gets its collection.case_meta
row — provenance inferred from what the case actually is — plus an assignment
record and an audit entry. Nothing about the cases themselves is copied.
"""

from __future__ import annotations

import asyncio

from sqlalchemy import text

from app.core.database import SessionFactory

# --- Types ---------------------------------------------------------------
# code, name, description, priority, queue, sla_h, duplicate_policy, approval, auto_close
CASE_TYPES = [
    ("COLLECTION", "Collection", "Standard collection on an overdue balance.",
     "Medium", "EARLY_STAGE", 24, "OPEN_EXISTING", False, True),
    ("BROKEN_PTP", "Broken Promise", "A promise to pay was missed.",
     "High", "BROKEN_PROMISE", 8, "CREATE_CHILD", False, True),
    ("PAYMENT_FAILURE", "Payment Failure", "A payment attempt failed or reversed.",
     "High", "EARLY_STAGE", 8, "MERGE", False, True),
    ("HIGH_RISK", "High Risk", "Risk engine flagged the account.",
     "High", "HIGH_RISK", 8, "OPEN_EXISTING", False, False),
    ("HIGH_DPD", "High DPD", "Account crossed a delinquency threshold.",
     "High", "LATE_STAGE", 8, "OPEN_EXISTING", False, True),
    ("DISPUTE", "Dispute", "Customer disputes the balance or a charge.",
     "High", "DISPUTES", 48, "OPEN_EXISTING", False, False),
    ("PAYMENT_PLAN", "Payment Plan", "Negotiating or servicing an arrangement.",
     "Medium", "EARLY_STAGE", 24, "OPEN_EXISTING", False, True),
    ("LEGAL_FOLLOWUP", "Legal Follow-up", "Pre-legal or legal action in progress.",
     "Critical", "LEGAL", 4, "OPEN_EXISTING", True, False),
    ("AGENCY_RECALL", "Agency Recall", "Placement is due for recall or review.",
     "Medium", "AGENCY", 24, "OPEN_EXISTING", False, False),
    ("BILLING_ISSUE", "Billing Issue", "Billing correction needed before collection.",
     "Medium", "DISPUTES", 48, "MERGE", False, False),
]

# --- Sources -------------------------------------------------------------
CASE_SOURCES = [
    ("AGENT_MANUAL", "Collection Agent", "Raised by an agent from the workspace.", False),
    ("SUPERVISOR_MANUAL", "Supervisor", "Raised by a supervisor.", False),
    ("STRATEGY", "Strategy Engine", "Generated by a dunning strategy step.", True),
    ("BROKEN_PTP", "Broken PTP", "Raised automatically when a promise broke.", True),
    ("PAYMENT_FAILURE", "Payment Failure", "Raised on a failed or reversed payment.", True),
    ("HIGH_RISK", "Risk Engine", "Raised when the risk score crossed its threshold.", True),
    ("HIGH_DPD", "Ageing Monitor", "Raised when the account crossed a DPD band.", True),
    ("DISPUTE_ESCALATION", "Dispute Escalation", "Escalated from a dispute.", True),
    ("LEGAL_ESCALATION", "Legal Escalation", "Escalated to or from legal.", True),
    ("AGENCY_ESCALATION", "Agency Escalation", "Raised from agency placement activity.", True),
    ("EXTERNAL_API", "External API", "Created by an upstream system.", True),
    ("SYSTEM_WORKFLOW", "System Workflow", "Raised by an internal scheduled workflow.", True),
]

# --- Priorities ----------------------------------------------------------
PRIORITIES = [
    ("Critical", "Critical", 1, 4, "destructive"),
    ("High", "High", 2, 8, "warning"),
    ("Medium", "Medium", 3, 24, "info"),
    ("Low", "Low", 4, 48, "muted"),
]

# --- Queues --------------------------------------------------------------
# code, name, description, dpd_min, dpd_max, amt_min, amt_max, risks, types, mode, max
QUEUES = [
    ("EARLY_STAGE", "Early Stage", "1–30 days past due. Soft, high-volume contact.",
     1, 30, None, None, [], [], "ROUND_ROBIN", 60),
    ("LATE_STAGE", "Late Stage", "31–90 days. Negotiation and arrangements.",
     31, 90, None, None, [], [], "LEAST_LOADED", 45),
    ("HIGH_RISK", "High Risk", "High and Critical risk regardless of ageing.",
     None, None, None, None, ["High", "Critical"], [], "SKILL_BASED", 30),
    ("HIGH_VALUE", "High Value", "Balances above $2,000 — senior collectors.",
     None, None, 2000, None, [], [], "SKILL_BASED", 25),
    ("BROKEN_PROMISE", "Broken Promise", "Promises that were not kept.",
     None, None, None, None, [], [], "LEAST_LOADED", 40),
    ("ENTERPRISE", "Enterprise", "Corporate accounts and their subscribers.",
     None, None, None, None, [], ["ENTERPRISE"], "SKILL_BASED", 30),
    ("DISPUTES", "Disputes", "Balance is contested; collection is on hold.",
     None, None, None, None, [], [], "SKILL_BASED", 35),
    ("LEGAL", "Legal", "Pre-legal and legal matters.",
     91, None, None, None, ["Critical"], [], "MANUAL", 20),
    ("AGENCY", "Agency", "Placed with an external agency; monitoring only.",
     None, None, None, None, [], [], "MANUAL", 100),
]

# --- Workflow ------------------------------------------------------------
# code, name, category, initial, terminal, pauses_sla, colour
STATES = [
    ("NEW", "New", "OPEN", True, False, False, "info"),
    ("ASSIGNED", "Assigned", "OPEN", False, False, False, "info"),
    ("IN_PROGRESS", "In Progress", "OPEN", False, False, False, "primary"),
    ("PENDING_CUSTOMER", "Pending Customer", "PENDING", False, False, True, "warning"),
    ("PENDING_PAYMENT", "Pending Payment", "PENDING", False, False, True, "warning"),
    ("MONITORING_PTP", "Monitoring PTP", "PENDING", False, False, True, "info"),
    ("ESCALATED", "Escalated", "ESCALATED", False, False, False, "warning"),
    ("LEGAL", "Legal", "ESCALATED", False, False, True, "purple"),
    ("AGENCY", "Agency", "ESCALATED", False, False, True, "purple"),
    ("RESOLVED", "Resolved", "CLOSED", False, False, False, "success"),
    ("CLOSED", "Closed", "CLOSED", False, True, False, "muted"),
    ("CANCELLED", "Cancelled", "CANCELLED", False, True, False, "muted"),
    ("REOPENED", "Reopened", "OPEN", False, False, False, "warning"),
]

# from, to, label, permission, requires_note, requires_approval
TRANSITIONS = [
    ("NEW", "ASSIGNED", "Assign", "caseAssign", False, False),
    ("NEW", "IN_PROGRESS", "Start work", "caseManagement", False, False),
    ("NEW", "CANCELLED", "Cancel", "caseClose", True, False),
    ("ASSIGNED", "IN_PROGRESS", "Start work", "caseManagement", False, False),
    ("ASSIGNED", "ASSIGNED", "Transfer", "caseTransfer", True, False),
    ("ASSIGNED", "CANCELLED", "Cancel", "caseClose", True, False),
    ("IN_PROGRESS", "PENDING_CUSTOMER", "Awaiting customer", "caseManagement", True, False),
    ("IN_PROGRESS", "PENDING_PAYMENT", "Awaiting payment", "caseManagement", False, False),
    ("IN_PROGRESS", "MONITORING_PTP", "Promise taken", "caseManagement", False, False),
    ("IN_PROGRESS", "ESCALATED", "Escalate", "caseEscalate", True, False),
    ("IN_PROGRESS", "RESOLVED", "Resolve", "caseManagement", True, False),
    ("IN_PROGRESS", "CANCELLED", "Cancel", "caseClose", True, False),
    ("PENDING_CUSTOMER", "IN_PROGRESS", "Customer responded", "caseManagement", False, False),
    ("PENDING_CUSTOMER", "ESCALATED", "No response — escalate", "caseEscalate", True, False),
    ("PENDING_PAYMENT", "RESOLVED", "Payment received", "caseManagement", False, False),
    ("PENDING_PAYMENT", "IN_PROGRESS", "Payment not received", "caseManagement", False, False),
    ("MONITORING_PTP", "RESOLVED", "Promise kept", "caseManagement", False, False),
    ("MONITORING_PTP", "IN_PROGRESS", "Promise broken", "caseManagement", True, False),
    ("MONITORING_PTP", "ESCALATED", "Promise broken — escalate", "caseEscalate", True, False),
    ("ESCALATED", "IN_PROGRESS", "Return to collection", "caseManagement", True, False),
    ("ESCALATED", "LEGAL", "Refer to legal", "caseEscalate", True, True),
    ("ESCALATED", "AGENCY", "Place with agency", "caseEscalate", True, True),
    ("ESCALATED", "RESOLVED", "Resolve", "caseManagement", True, False),
    ("LEGAL", "RESOLVED", "Legal resolved", "caseManagement", True, False),
    ("LEGAL", "CLOSED", "Close — written off", "caseClose", True, True),
    ("AGENCY", "RESOLVED", "Recovered by agency", "caseManagement", True, False),
    ("AGENCY", "IN_PROGRESS", "Recalled from agency", "caseManagement", True, False),
    ("AGENCY", "LEGAL", "Agency exhausted — legal", "caseEscalate", True, True),
    ("RESOLVED", "CLOSED", "Close", "caseClose", False, False),
    ("RESOLVED", "REOPENED", "Reopen", "caseReopen", True, False),
    ("CLOSED", "REOPENED", "Reopen", "caseReopen", True, False),
    ("REOPENED", "IN_PROGRESS", "Resume work", "caseManagement", False, False),
    ("REOPENED", "ASSIGNED", "Reassign", "caseAssign", False, False),
]

# --- Assignment rules ----------------------------------------------------
# name, priority, type, source, dpd_min, dpd_max, amt_min, amt_max, risks, cust_types, queue, set_priority
RULES = [
    ("Legal follow-up to the legal desk", 10, "LEGAL_FOLLOWUP", None, None, None,
     None, None, [], [], "LEGAL", "Critical"),
    ("Disputes hold collection", 20, "DISPUTE", None, None, None,
     None, None, [], [], "DISPUTES", "High"),
    ("Broken promises to the recovery pool", 30, "BROKEN_PTP", None, None, None,
     None, None, [], [], "BROKEN_PROMISE", "High"),
    ("Agency matters to the agency desk", 40, "AGENCY_RECALL", None, None, None,
     None, None, [], [], "AGENCY", None),
    ("Critical risk to specialists", 50, None, None, None, None,
     None, None, ["Critical"], [], "HIGH_RISK", "Critical"),
    ("Balances over $2,000 to senior collectors", 60, None, None, None, None,
     2000, None, [], [], "HIGH_VALUE", "High"),
    ("Enterprise accounts to the corporate desk", 70, None, None, None, None,
     None, None, [], ["ENTERPRISE"], "ENTERPRISE", None),
    ("90+ days to late stage", 80, None, None, 91, None,
     None, None, [], [], "LATE_STAGE", "High"),
    ("31–90 days to late stage", 90, None, None, 31, 90,
     None, None, [], [], "LATE_STAGE", "Medium"),
    ("Everything else to early stage", 999, None, None, None, None,
     None, None, [], [], "EARLY_STAGE", "Medium"),
]

# How an existing case's type and status map onto provenance and workflow state.
SOURCE_FOR_TYPE = {
    "Broken PTP": "BROKEN_PTP",
    "Dispute": "DISPUTE_ESCALATION",
    "Legal Followup": "LEGAL_ESCALATION",
    "Payment Plan": "AGENT_MANUAL",
    "Billing Issue": "AGENT_MANUAL",
    "Collection": "STRATEGY",
}
TYPE_FOR_LEGACY = {
    "Collection": "COLLECTION",
    "Broken PTP": "BROKEN_PTP",
    "Dispute": "DISPUTE",
    "Legal Followup": "LEGAL_FOLLOWUP",
    "Payment Plan": "PAYMENT_PLAN",
    "Billing Issue": "BILLING_ISSUE",
}
STATE_FOR_STATUS = {
    "OPEN": "NEW",
    "IN_PROGRESS": "IN_PROGRESS",
    "ESCALATED": "ESCALATED",
    "LEGAL": "LEGAL",
    "CLOSED": "CLOSED",
}


async def main() -> None:
    async with SessionFactory() as db:
        # ---------- Reference data ----------
        for c, n, d, p, q, sla, dup, appr, auto in CASE_TYPES:
            await db.execute(text("""
                INSERT INTO collection.case_type
                  (code, name, description, default_priority, default_queue, sla_hours,
                   duplicate_policy, requires_approval, auto_close_on_pay, sort_order)
                VALUES (:c,:n,:d,:p,:q,:sla,:dup,:appr,:auto,:o)
                ON CONFLICT (code) DO UPDATE SET name=EXCLUDED.name,
                  description=EXCLUDED.description, default_priority=EXCLUDED.default_priority,
                  default_queue=EXCLUDED.default_queue, sla_hours=EXCLUDED.sla_hours,
                  duplicate_policy=EXCLUDED.duplicate_policy"""),
                dict(c=c, n=n, d=d, p=p, q=q, sla=sla, dup=dup, appr=appr, auto=auto,
                     o=CASE_TYPES.index((c, n, d, p, q, sla, dup, appr, auto)) * 10))

        for i, (c, n, d, auto) in enumerate(CASE_SOURCES):
            await db.execute(text("""
                INSERT INTO collection.case_source (code, name, description, is_automated, sort_order)
                VALUES (:c,:n,:d,:a,:o)
                ON CONFLICT (code) DO UPDATE SET name=EXCLUDED.name,
                  description=EXCLUDED.description, is_automated=EXCLUDED.is_automated"""),
                dict(c=c, n=n, d=d, a=auto, o=i * 10))

        for c, n, rank, sla, colour in PRIORITIES:
            await db.execute(text("""
                INSERT INTO collection.case_priority (code, name, rank, sla_hours, colour)
                VALUES (:c,:n,:r,:s,:col)
                ON CONFLICT (code) DO UPDATE SET rank=EXCLUDED.rank, sla_hours=EXCLUDED.sla_hours"""),
                dict(c=c, n=n, r=rank, s=sla, col=colour))

        for i, (c, n, d, dmin, dmax, amin, amax, risks, ctypes, mode, mx) in enumerate(QUEUES):
            await db.execute(text("""
                INSERT INTO collection.case_queue
                  (code, name, description, dpd_min, dpd_max, amount_min, amount_max,
                   risk_levels, customer_types, assignment_mode, max_per_agent, sort_order)
                VALUES (:c,:n,:d,:dmin,:dmax,:amin,:amax,:risks,:ctypes,:mode,:mx,:o)
                ON CONFLICT (code) DO UPDATE SET name=EXCLUDED.name,
                  description=EXCLUDED.description, assignment_mode=EXCLUDED.assignment_mode"""),
                dict(c=c, n=n, d=d, dmin=dmin, dmax=dmax, amin=amin, amax=amax,
                     risks=risks, ctypes=ctypes, mode=mode, mx=mx, o=i * 10))

        # ---------- Workflow ----------
        await db.execute(text("""
            INSERT INTO collection.workflow (code, name, description, is_default)
            VALUES ('STANDARD', 'Standard Collection Workflow',
                    'The default lifecycle for every collection case.', TRUE)
            ON CONFLICT (code) DO NOTHING"""))
        for i, (c, n, cat, init, term, pause, colour) in enumerate(STATES):
            await db.execute(text("""
                INSERT INTO collection.workflow_state
                  (workflow_code, code, name, category, is_initial, is_terminal,
                   pauses_sla, colour, sort_order)
                VALUES ('STANDARD',:c,:n,:cat,:init,:term,:pause,:col,:o)
                ON CONFLICT (workflow_code, code) DO UPDATE SET name=EXCLUDED.name,
                  category=EXCLUDED.category, pauses_sla=EXCLUDED.pauses_sla"""),
                dict(c=c, n=n, cat=cat, init=init, term=term, pause=pause, col=colour, o=i * 10))
        for i, (f, t, label, perm, note, appr) in enumerate(TRANSITIONS):
            await db.execute(text("""
                INSERT INTO collection.workflow_transition
                  (workflow_code, from_state, to_state, label, required_permission,
                   requires_note, requires_approval, sort_order)
                VALUES ('STANDARD',:f,:t,:l,:p,:n,:a,:o)
                ON CONFLICT (workflow_code, from_state, to_state) DO UPDATE
                  SET label=EXCLUDED.label, required_permission=EXCLUDED.required_permission,
                      requires_note=EXCLUDED.requires_note"""),
                dict(f=f, t=t, l=label, p=perm, n=note, a=appr, o=i * 10))

        # ---------- Assignment rules ----------
        await db.execute(text("DELETE FROM collection.assignment_rule"))
        for (name, pri, ctype, src, dmin, dmax, amin, amax, risks, ctypes, queue, setp) in RULES:
            await db.execute(text("""
                INSERT INTO collection.assignment_rule
                  (name, priority, case_type_code, source_code, dpd_min, dpd_max,
                   amount_min, amount_max, risk_levels, customer_types, target_queue, set_priority)
                VALUES (:n,:p,:ct,:s,:dmin,:dmax,:amin,:amax,:risks,:ctypes,:q,:setp)"""),
                dict(n=name, p=pri, ct=ctype, s=src, dmin=dmin, dmax=dmax, amin=amin,
                     amax=amax, risks=risks, ctypes=ctypes, q=queue, setp=setp))

        # ---------- Backfill the existing case book ----------
        cases = (await db.execute(text("""
            SELECT dc.id, dc.case_code, dc.case_type_code, dc.status, dc.priority,
                   dc.assigned_agent_id, dc.opened_at, dc.strategy_id, dc.amount, dc.dpd,
                   dc.customer_id, dc.account_id, c.customer_type, c.risk_level
            FROM customer_schema.debt_case dc
            JOIN customer_schema.customer c ON c.id = dc.customer_id
            ORDER BY dc.id"""))).mappings().all()

        made = 0
        for r in cases:
            legacy_type = r["case_type_code"]
            source = SOURCE_FOR_TYPE.get(legacy_type, "STRATEGY")
            # A case with no agent was never routed by a human.
            if r["assigned_agent_id"] is None:
                source = "SYSTEM_WORKFLOW"
            state = STATE_FOR_STATUS.get(r["status"], "IN_PROGRESS")
            if state == "NEW" and r["assigned_agent_id"]:
                state = "ASSIGNED"

            # Route through the same rules a new case would use.
            queue = (await db.execute(text("""
                SELECT target_queue FROM collection.assignment_rule
                WHERE is_active
                  AND (case_type_code IS NULL OR case_type_code = :ct)
                  AND (dpd_min IS NULL OR :dpd >= dpd_min)
                  AND (dpd_max IS NULL OR :dpd <= dpd_max)
                  AND (amount_min IS NULL OR :amt >= amount_min)
                  AND (amount_max IS NULL OR :amt <= amount_max)
                  AND (cardinality(risk_levels) = 0 OR :risk = ANY(risk_levels))
                  AND (cardinality(customer_types) = 0 OR :ctype = ANY(customer_types))
                ORDER BY priority LIMIT 1"""),
                dict(ct=TYPE_FOR_LEGACY.get(legacy_type, "COLLECTION"), dpd=r["dpd"],
                     amt=r["amount"], risk=r["risk_level"], ctype=r["customer_type"]))
            ).scalar_one_or_none() or "EARLY_STAGE"

            await db.execute(text("""
                INSERT INTO collection.case_meta
                  (case_id, source_code, trigger_detail, created_by_user, created_by_role,
                   queue_code, workflow_code, workflow_state, due_date, strategy_id)
                VALUES (:id,:src,:trig,:by,:role,:q,'STANDARD',:state,
                        (CAST(:opened AS date) + 7), :strat)
                ON CONFLICT (case_id) DO UPDATE SET
                  source_code=EXCLUDED.source_code, queue_code=EXCLUDED.queue_code,
                  workflow_state=EXCLUDED.workflow_state, updated_at=now()"""),
                dict(id=r["id"], src=source,
                     trig=f"Migrated from the existing case book ({legacy_type}).",
                     by=r["assigned_agent_id"], role="AGENT" if r["assigned_agent_id"] else "SYSTEM",
                     q=queue, state=state, opened=r["opened_at"], strat=r["strategy_id"]))

            if r["assigned_agent_id"]:
                exists = (await db.execute(text("""
                    SELECT 1 FROM collection.case_assignment
                    WHERE case_id = :i AND released_at IS NULL"""), {"i": r["id"]})).first()
                if not exists:
                    await db.execute(text("""
                        INSERT INTO collection.case_assignment
                          (case_id, agent_id, queue_code, assigned_by, assignment_type,
                           reason, assigned_at)
                        VALUES (:i,:a,:q,:a,'AUTO','Routed on migration by assignment rules.',:t)"""),
                        dict(i=r["id"], a=r["assigned_agent_id"], q=queue, t=r["opened_at"]))

            await db.execute(text("""
                INSERT INTO collection.case_audit
                  (case_id, action, actor_id, actor_role, reason, occurred_at)
                VALUES (:i,'CASE_CREATED',:a,'SYSTEM',
                        'Case brought under Case Management.',:t)"""),
                dict(i=r["id"], a=r["assigned_agent_id"], t=r["opened_at"]))
            made += 1

        await db.commit()

        counts = {}
        for t in ("case_type", "case_source", "case_priority", "case_queue", "workflow_state",
                  "workflow_transition", "assignment_rule", "case_meta", "case_assignment",
                  "case_audit"):
            counts[t] = (await db.execute(text(f"SELECT count(*) FROM collection.{t}"))).scalar_one()
        for k, v in counts.items():
            print(f"  {k:<22} {v}")
        print(f"\n  {made} existing cases brought under Case Management (none duplicated)")

        dist = (await db.execute(text("""
            SELECT m.queue_code, count(*) FROM collection.case_meta m
            GROUP BY 1 ORDER BY 2 DESC"""))).all()
        print("  queue distribution:", ", ".join(f"{q} {n}" for q, n in dist))
        st = (await db.execute(text("""
            SELECT m.workflow_state, count(*) FROM collection.case_meta m
            GROUP BY 1 ORDER BY 2 DESC"""))).all()
        print("  workflow states:   ", ", ".join(f"{s} {n}" for s, n in st))


if __name__ == "__main__":
    asyncio.run(main())
